Repository canonical/specs.canonical.com, pull requests merged in 2022-10, with the labels that each got.

#90 abstract spec preview
  client/Error.tsx
  client/SpecCard.tsx
  client/SpecsDetails.tsx
  client/styles.scss
  client/types.ts
  package.json
  requirements.txt
  webapp/app.py
  webapp/settings.py
  webapp/spec.py
  webapp/spreadsheet.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#91 Spec frontend tests
  .gitignore
  babel.config.js
  client/tests/App.test.tsx
  client/tests/Error.test.tsx
  client/tests/Filters.test.tsx
  client/tests/Search.test.tsx
  client/tests/SpecCard.test.tsx
  client/tests/SpecDetails.test.tsx
  client/tests/__mocks__/utils.ts
  client/types.ts
  jest.config.js
  jest.setup.js
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#97 [client/SpecDetails] fix: don't name the target to load the spec in
  client/SpecsDetails.tsx
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1
