Repository canonical/specs.canonical.com, pull requests merged in 2022-11, with the labels that each got.

#100 Add update command
  .env
  Dockerfile.update
  konf/cronjob-update.yaml
  webapp/app.py
  webapp/contants.py
  webapp/google.py
  webapp/spec.py
  webapp/spreadsheet.py
  webapp/update.py
  yarn.lock
Labels: Review: Code +1

#101 fix yaml format
  konf/cronjob-update.yaml
Labels: Review: Code +1

#102 change FLASK_APP env var
  Dockerfile.update
Labels: Review: Code +1

#103 feat: automatically turn spec_name to uppercase
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#104 Add readme
  README.md
Labels: Review: QA +1

#106 feat: add a new spec link to docs
  client/App.tsx
Labels: Review: QA +1, Review: Code +1

#109 remove google script WD-764
  googlescript/README.md
  googlescript/code.js
Labels: Review: Code +1
