Repository canonical/specs.canonical.com, pull requests merged in 2023-02, with the labels that each got.

#126 Add dev dependencies
  requirements.txt
Labels: Review: Code +1

#127 Run update cronjob less often
  konf/cronjob-update.yaml
Labels: Review: Code +1

#128 WD-2246 Render an index of a spec which is longer then 5 characters
  client/App.tsx
  client/SpecCard.tsx
  client/tests/SpecCard.test.tsx
  client/tests/__mocks__/utils.ts
Labels: Review: QA needed, Review: Code needed

#129 WD-2332 Improve unknown spec status reporting
  client/SpecsDetails.tsx
  client/tests/SpecDetails.test.tsx
  client/types.ts
  webapp/spec.py
  webapp/update.py
Labels: Review: QA +1, Review: Code +1
